### ISSUE TITLE
train throttle too?

### ISSUE THREAD

**Issue by Xunzhaocunzi** [naokishibuya/car-behavioral-cloning#14]
It looks like only the steering angle was trained in the model, Not throttle. 

Did you try to update your train model to make it have 2 outputs, one for steering, and the other for throttle? 

Thank you.

**Comment by naokishibuya** [comment]
Hi @Xunzhaocunzi 
Yes, you're right - the training is only for steering angle.  I did not try training with 2 outputs.  I'd imagine you'd need to feed the speed as part of the input or maybe a sequence of image frames rather than just one image at a time......but I'm only guessing here.   Why don't you try for yourself and let the world know how it goes!

**Comment by nikhilt44** [comment]
Hey,

So i was going through the project and had a doubt regarding the speed of the car. How did you get the speed in the autonomous mode?

**Comment by naokishibuya** [comment]
Hi @nikhilt44 
The speed is coming from the Udacity's simulator.  See the drive.py that reads "speed" from the incoming message from the simulator.

```python
        # The current speed of the car
        speed = float(data["speed"])
```
