### ISSUE TITLE
Can't save image data

### ISSUE THREAD

**Issue by n1try** [naokishibuya/car-behavioral-cloning#9]
I'm getting the following error when specifying an output directory.

```python
    ...
    File "drive.py", line 66, in telemetry
        image.save('{}.jpg'.format(image_filename))
AttributeError: 'numpy.ndarray' object has no attribute 'save'
```

**Comment by naokishibuya** [comment]
Hi @n1try 
Thanks for reporting this.  I think I was saving image frames at some points for debugging purpose but then later stop using it.  

Originally, I had `image` for the PIL image object and `image_array` for numpy array so calling `image.save` was calling the PIL save method but later I refactored the code and made `image` to be numpy array and caused this problem.  

I'm guessing you could move the following codes:

```python
        # save frame
        if args.image_folder != '':
            timestamp = datetime.utcnow().strftime('%Y_%m_%d_%H_%M_%S_%f')[:-3]
            image_filename = os.path.join(args.image_folder, timestamp)
            image.save('{}.jpg'.format(image_filename))
```

to just after the below code:

```python
        # The current image from the center camera of the car
        image = Image.open(BytesIO(base64.b64decode(data["image"])))
```

So that it will call the PIL image save method like below.

```python
        # The current image from the center camera of the car
        image = Image.open(BytesIO(base64.b64decode(data["image"])))
        # save frame
        if args.image_folder != '':
            timestamp = datetime.utcnow().strftime('%Y_%m_%d_%H_%M_%S_%f')[:-3]
            image_filename = os.path.join(args.image_folder, timestamp)
            image.save('{}.jpg'.format(image_filename))
```

If you need this functionality, please try this change.  If it works, please send me a pull request for merging.  If no one is interested in this function, I should probably remove it to avoid future confusion.

**Comment by naokishibuya** [comment]
thanks @n1try !
